name: Codelists Generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CL_CODELIST: "csv_codelists/glosis_cl.csv"
    PROC_CODELIST: "csv_codelists/glosis_procedure.csv"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd utils/transformer_tool
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git clone https://github.com/Montanaz0r/pytarql.git
        cd pytarql
        pip install .
    - name: Generate codelists
      run: |
        cd utils/transformer_tool
        python transform_to_csv.py ../../glosis_cl.ttl ../../csv_codelists/glosis_cl
        python transform_to_csv.py ../../glosis_procedure.ttl ../../csv_codelists/glosis_procedure
    - name: Commit codelists
      if: ${{ success() }}
      uses: EndBug/add-and-commit@v9
      with:
          add: "['${{ env.CL_CODELIST }}', '${{ env.PROC_CODELIST }}']"
          message: "codelists generated automatically"
